version: "3.9"

volumes:
  db-data:

services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/code
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - db
      - webpacker
      - maildev

  webpacker:
    build: .
    command: bash -c "yarn install && ./bin/webpack-dev-server --inline true"
    ports:
        - "3035:3035"
    volumes:
        - .:/code
    restart: unless-stopped

  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

  maildev:
    image: "maildev/maildev"
    ports:
      - "1080:80"



