test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

yandex:
  service: S3
  access_key_id: <%= Rails.application.credentials.dig(:yc, :access_key_id) %>
  secret_access_key: <%= Rails.application.credentials.dig(:yc, :secret_access_key) %>
  region: ru-central1
  bucket: event-app-rails-6
  endpoint: 'https://storage.yandexcloud.net'

# mirror:
#   service: Mirror
#   primary: local
#   mirrors: [ amazon, google, microsoft ]
